import { i18n } from '@/services/i18n';

export function getInitialState(): any[] {
  return [
    {
      id: 'todo',
      title: i18n.get('To-do'),
      name: 'todo',
      pageCount: 2,
      canCreate: true,
      loading: false,
      records: [
        {
          notes:
            'Nisi ut pariatur occaecat nulla sunt id cupidatat. Sint exercitation culpa enim eiusmod sunt proident. Dolor eu consequat reprehenderit in culpa occaecat. Magna sit velit est do veniam sunt culpa officia mollit.',
          endDate: '2025-04-27T18:30Z',
          name: 'Testing',
          progress: 0,
          id: 26,
          state: 'todo',
          priority: 0,
          version: 3,
          user: { name: 'Administrator', id: 1, $version: 41 },
          startDate: '2025-04-18T18:30Z',
          attrs: null,
        },
        {
          notes:
            'Velit ex ullamco reprehenderit proident nisi ullamco adipisicing. Quis laborum duis eiusmod esse. Qui aute voluptate id ad sunt nisi voluptate ad eiusmod.',
          endDate: '2025-04-14T18:30Z',
          name: 'Development',
          progress: 0,
          id: 35,
          state: 'todo',
          priority: 1,
          version: 2,
          user: { name: 'Demo User', id: 2, $version: 1 },
          startDate: '2025-03-29T18:30Z',
          attrs: null,
        },
      ],
    },
    {
      id: 'progress',
      title: i18n.get('In progress'),
      name: 'progress',
      pageCount: 5,
      loading: false,
      records: [
        {
          notes: null,
          endDate: '2025-05-06T18:30Z',
          name: 'Completion',
          progress: 0,
          id: 25,
          state: 'progress',
          priority: 1,
          version: 3,
          user: { name: 'Administrator', id: 1, $version: 41 },
          startDate: '2025-05-02T18:30Z',
          attrs: null,
        },
        {
          notes: null,
          endDate: '2026-01-15T16:45:22Z',
          name: 'Post Launch',
          progress: 0,
          id: 19,
          state: 'progress',
          priority: 2,
          version: 6,
          user: { name: 'Administrator', id: 1, $version: 41 },
          startDate: '2025-11-19T15:52Z',
          attrs: null,
        },
        {
          notes: null,
          endDate: '2025-11-08T18:30Z',
          name: 'Launch 123',
          progress: 15,
          id: 18,
          state: 'progress',
          priority: 3,
          version: 6,
          user: { name: 'Administrator', id: 1, $version: 41 },
          startDate: '2025-11-06T18:30Z',
          attrs: null,
        },
        {
          notes: 'Apud has gentes, quarum exordiens initium ab',
          endDate: '2025-11-04T18:30Z',
          name: 'Design',
          progress: 20,
          id: 37,
          state: 'progress',
          priority: 4,
          version: 4,
          user: { name: 'Administrator', id: 1, $version: 41 },
          startDate: '2025-10-23T18:30Z',
          attrs: null,
        },
        {
          notes: null,
          endDate: '2025-04-03T18:30Z',
          name: 'Design',
          progress: 0,
          id: 38,
          state: 'progress',
          priority: 5,
          version: 5,
          user: { name: 'Demo User', id: 2, $version: 1 },
          startDate: '2025-03-14T18:30Z',
          attrs: null,
        },
      ],
    },
    {
      id: 'complete',
      title: i18n.get('Completed'),
      name: 'complete',
      pageCount: 1,
      loading: false,
      records: [
        {
          notes:
            'Lorem tempor deserunt minim occaecat aliquip cillum. Dolor pariatur officia elit id. Adipisicing duis anim dolor mollit nisi sit non dolore dolor. Adipisicing esse qui ullamco id duis.',
          endDate: '2025-03-20T18:30Z',
          name: 'Definition 12345678',
          progress: 100,
          id: 34,
          state: 'complete',
          priority: 57,
          version: 53,
          user: { name: 'Administrator', id: 1, $version: 41 },
          startDate: '2025-03-14T18:30Z',
          attrs: null,
        },
      ],
    },
  ];
}
